Repository MIT-Emerging-Talent/ET6-CDSP-group-03-repo, pull requests merged in 2025-07, with the labels that each got.

#42 Add cleaned separate datasets
  1_datasets/data/clean_datasets/fivc_gaza_october_cleaned.csv
  1_datasets/data/clean_datasets/gaza_displacement_cleaned.csv
  1_datasets/data/clean_datasets/gaza_displacement_cleaned.json
  1_datasets/data/clean_datasets/idmc_event_data_for_pse_cleaned.csv
  1_datasets/data/clean_datasets/infrastructure_damaged_clean.csv
  1_datasets/data/clean_datasets/palestine_israel_war_cleaned_data.csv
  2_data_preparation/notebooks/casualties_data_cleaning_notebook.ipynb
  2_data_preparation/notebooks/data_cleaning_notebook_template.ipynb
  2_data_preparation/notebooks/food_insecurity_and_violent_conflict_gaza_data_cleaning.ipynb
  2_data_preparation/notebooks/gaza-displacement_cleaning.ipynb
  2_data_preparation/notebooks/gaza_infastructure_damage_data_cleaning.ipynb
  2_data_preparation/notebooks/idmc_event_data_for_pse_cleaned_csv_notebook (1).ipynb
  2_data_preparation/notebooks/palestine_israel_conflict_cleaning_notebook.ipynb
  2_data_preparation/notebooks/requirements.txt
Labels: enhancement

#52 Data analysis/displacement orders
  3_data_exploration/notebooks/displacement_orders_EDA.ipynb
Labels: Data Analysis

#57 Data analysis/infrastructure damaged
  3_data_exploration/infrastracture_damaged_analysis.ipynb
Labels: Data Analysis

#58 Readme update 1
  README.md
Labels: Data Analysis

#64 Non technical document
  4_data_analysis/README.md
  4_data_analysis/non_technical_results.md
  4_data_analysis/plots_images/plot_eight.png
  4_data_analysis/plots_images/plot_eighteen.png
  4_data_analysis/plots_images/plot_eleven.png
  4_data_analysis/plots_images/plot_fifteen.png
  4_data_analysis/plots_images/plot_five.png
  4_data_analysis/plots_images/plot_four.png
  4_data_analysis/plots_images/plot_fourteen.png
  4_data_analysis/plots_images/plot_nine.png
  4_data_analysis/plots_images/plot_nineteen.png
  4_data_analysis/plots_images/plot_one.png
  4_data_analysis/plots_images/plot_seven.png
  4_data_analysis/plots_images/plot_seventeen.png
  4_data_analysis/plots_images/plot_six.png
  4_data_analysis/plots_images/plot_sixteen.png
  4_data_analysis/plots_images/plot_ten.png
  4_data_analysis/plots_images/plot_thirteen.png
  4_data_analysis/plots_images/plot_three.png
  4_data_analysis/plots_images/plot_twelve.png
  4_data_analysis/plots_images/plot_twenty.png
  4_data_analysis/plots_images/plot_twenty_one.png
  4_data_analysis/plots_images/plot_twenty_three.png
  4_data_analysis/plots_images/plot_twenty_two.png
  4_data_analysis/plots_images/plot_two.png
Labels: Data Analysis

#62 Technical description adding
  4_data_analysis/technical_description.md
Labels: Data Analysis

#68 adding milestone 3 retrospective
  collaboration/retrospectives/3_data_analysis.md
Labels: documentation

#73 Adding a summary for data analysis readme
  4_data_analysis/README.md
Labels: documentation

#79 Fix 0 domain links
  0_domain_study/README.md
  0_domain_study/resources/Education in Conflict/links.md
  0_domain_study/resources/Impact of AI on Uni Students/links.md
Labels: bug, documentation

#84 fixing links
  2_data_preparation/README.md
  4_data_analysis/README.md
Labels: bug, documentation
